import sys
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pipeline_api
from pipeline_api import annotate_commit

# In-memory store to replace HelixDB
mock_memories = {}

def mock_write(func_id, commit_sha, edge_type, memory_text):
    if func_id not in mock_memories:
        mock_memories[func_id] = []
    
    # We skip embedding generation here to save time and API costs,
    # we just need the structural edges and text for the test.
    entry = {
        "state_id": f"state_{func_id}_{commit_sha[:7]}",
        "commit_sha": commit_sha,
        "memory": memory_text,
        "edge_type": edge_type,
    }
    mock_memories[func_id].append(entry)
    print(f"  [MOCK DB] Wrote memory for {func_id} via {edge_type}")
    return {"ok": True, "func_id": func_id, "state_id": entry["state_id"], "edge_type": edge_type, "error": None}

def mock_read(func_id):
    return mock_memories.get(func_id, [])

# Monkey-patch pipeline_api so we don't need HelixDB
pipeline_api.write_function_memory = mock_write
pipeline_api.read_function_memory_history = mock_read

# Our carefully chosen 5 commits
commits_to_test = [
    "78fac57", # feat(memory): implement phase 1 local memory engine
    "eca9f17", # fix(memory): harden phase 1 retrieval quality
    "8351639", # feat(graph): pivot memory runtime to Kuzu GraphRAG
    "6f9d6c6", # refactor(memory): move hybrid memory service into package
    "da80013"  # refactor(memory): extract hybrid retrieval mixin
]

print("Starting LLM annotation pipeline on real AMO commits (without HelixDB)...")
for sha in commits_to_test:
    print(f"\n{'='*50}\nProcessing commit: {sha}")
    result = annotate_commit(sha, debug=False)
    
    # Print the specific annotations generated by the LLM
    print(f"Annotated {len(result['annotated'])} functions:")
    for ann in result['annotated']:
        print(f"  - {ann.get('func_id')}: [{ann.get('edge_type')}] {ann.get('memory')}")
    
    if result.get('skipped'):
        print(f"Skipped {len(result['skipped'])} functions (trivial/new).")
    
    if result.get('errors'):
        print(f"Errors: {result['errors']}")

print("\n\n" + "="*50)
print("Final Mock DB State (Real LLM generated semantic timeline):")
print(json.dumps(mock_memories, indent=2))
